apiVersion: apps/v1
kind: Deployment
metadata:
  name: myntra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myntra
  template:
    metadata:
      labels:
        app: myntra
    spec:
      containers:
      - name: myntra
        image: sevenajay/myntra:latest
        ports:
        - containerPort: 3000   # Use port 3000
