apiVersion: apps/v1
kind: Deployment
metadata:
  name: myntra
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myntra
  template:
    metadata:
      labels:
        app: myntra
    spec:
      containers:
      - name: myntra
        #image: sevenajay/myntra:latest
        image: rover102/myntra-clone-app-01:ReplaceImageTag
        ports:
        - containerPort: 3000   # Use port 3000
