apiVersion: v1
kind: Service
metadata:
  name: myntra-clone-app-service-resource
  namespace: apps101
spec:
  selector:
    app: myntra
  ports:
  - protocol: TCP
    port: 80                 # Expose port 80
    targetPort: 3000
  type: LoadBalancer
